name: JDDock

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: List files and create directories
        run: |
          pwd && ls && mkdir -p downloads
          ls
      - name: Run Docker Container
        run: |
          docker run -d \
            --name jdownloader \
            -e JD_DEVICENAME="ACTIONJD" \
            -e JD_EMAIL="mrspidyxd@gmail.com" \
            -e JD_PASSWORD="Always hate me" \
            -v "$(pwd)/downloads:/jdownloader/downloads" \
            -v "$(pwd)/config:/jdownloader/cfg/" \
            antlafarge/jdownloader:ubuntu
      - name: Download and install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y ffmpeg
          wget -qq ${{ secrets.CONFIG }}
      - name: Building Image
        run:  docker build -t myjav .
      - name: Building Image
        run:  docker run -v "$(pwd)/downloads:/app/downloads"  myjav 
